name: rss_it_library
description: "Flutter plugin for parsing RSS/Atom/JSON feeds, powered by Go-based gofeed package"
version: 0.0.1

environment:
  sdk: ">=3.10.0"
  flutter: ">=3.38.2"

dependencies:
  flutter:
    sdk: flutter
  
  ffi: ^2.1.4
  plugin_platform_interface: ^2.1.8
  protobuf: ^5.1.0

dev_dependencies:
  ffigen: ^20.1.0
  flutter_lints: ^6.0.0

  # Testing
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true