name: rss_it_library
description: "Flutter plugin for parsing RSS/Atom/JSON feeds, powered by Go-based gofeed package"
version: 0.0.1

environment:
  sdk: ">=3.9.2"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  
  ffi: ^2.1.4
  plugin_platform_interface: ^2.1.8
  protobuf: ^5.1.0

dev_dependencies:
  ffigen: ^20.0.0
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true